# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.skt-phone.co.kr/")
    self.driver.set_window_size(653, 752)
    self.driver.find_element(By.CSS_SELECTOR, ".gnb_logo img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_menu > img").click()
    self.driver.find_element(By.LINK_TEXT, "안심통화 센터").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_menu > img").click()
    self.driver.find_element(By.LINK_TEXT, "T114 센터").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn_menu > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_menu > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "테마 에디터").click()
  
